spring:
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:true}
  swagger-ui:
    enabled: ${OPENAPI_ENABLED:true}

management:
  health:
    mail:
      enabled: false

logging:
  level:
    pe.edu.upt.fuerzaupt: INFO

app:
  mail:
    provider: ${APP_MAIL_PROVIDER:disabled}

