server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: lax

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN

